<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Create</title>
    <script type="text/javascript" src="/scripts.js"></script>
    <link href="/main.css" rel="stylesheet" />
</head>
<body>
    <textarea id="code_snippet">// write your code here</textarea>
    <div>
        <label>Time restriction:</label>
        <input id="time_restriction" type="text" value="0"/>
    </div>
    <div>
        <label>Views restriction:</label>
        <input id="views_restriction" type="text" value="0"/>
    </div>
    <button id="send_snippet" type="submit" onclick="send()">Submit</button>
</body>
</html>